"""Voice-clone preflight: gate a cloned voice BEFORE it renders thousands
of takes.

Stage-5 QC judges every take, but only after a full pass, and its remedy is
a re-roll. A fault in the voice prompt itself (reference audio + reference
transcript) is systematic: every take fails the same way and no re-roll can
fix it. 2026-09-04, Carnegie/Spader: the reference had no transcript
sidecar, whisper's auto-transcript hallucinated a phrase over the quiet
tail, and 2,420 takes (13 hours) opened with that phrase before anyone
listened. This module is the ten-minute check that would have caught it.

Two gates, run once per (voice audio, transcript, model) and cached:

1. Transcript vs audio. Whisper the reference with word times; any words
   heard after the speech energy ends are a hallucinated tail. If the
   transcript in use came from whisper, that is fatal (write a sidecar).
   Either way the transcript must agree with what whisper hears inside
   the voiced span.
2. Canary takes. Synthesize a few short public-domain sentences with the
   clone, transcribe them, and let the judge model rule on each exactly
   as stage-5 take review does (inserted content, skips, looping, start
   artifacts), with a WER fallback when Ollama is unreachable. Speaker
   similarity to the reference guards against a clone that drifts from
   the first take.

Language judgment (the verdicts) is the LLM's; deterministic code validates
and falls back, per project doctrine.
"""
from __future__ import annotations

import hashlib
import json
import re
import tempfile
import time
from pathlib import Path

import numpy as np

from pipeline.config import CFG, JUDGE_MODEL, ROOT, SAMPLE_RATE

PREFLIGHT_VERSION = 1
CACHE_DIR = ROOT / "voices" / ".preflight"
PREFLIGHT_CFG = dict(CFG.get("tts", {}).get("preflight") or {})

# Public domain (Patterson, 1925). Numbers spelled out so whisper cannot
# disagree with the source on digit rendering.
CANARY_TEXTS = [
    "At the time of my arrival, railhead had just reached Tsavo, about one hundred "
    "and thirty miles from the coast.",
    "Here it was found that a river crossed the route, fed from the everlasting snows "
    "of Kilimanjaro.",
    "The bridge had to be built, and the camps moved steadily forward through the "
    "wilderness, mile after mile.",
    "He wants respect. He wants to be remembered. There is no such thing as a small "
    "kindness.",
]


class VoicePreflightError(RuntimeError):
    """The cloned voice failed its preflight; rendering must not start."""


def _alpha(s: str) -> list[str]:
    return [t for t in re.sub(r"[^a-z' ]", " ", s.lower()).split() if t.strip("'")]


def _speech_end(path: Path, floor_db: float = -45.0, rel_db: float = 30.0) -> float:
    """Seconds at which voiced energy ends: last 20ms frame within rel_db of
    the loudest frame (and above an absolute floor)."""
    import soundfile as sf
    x, sr = sf.read(str(path), dtype="float32")
    if x.ndim > 1:
        x = x.mean(axis=1)
    n = int(sr * 0.02)
    frames = [x[i:i + n] for i in range(0, len(x) - n, n)]
    db = np.array([20 * np.log10(np.sqrt(np.mean(f ** 2)) + 1e-9) for f in frames])
    thresh = max(db.max() - rel_db, floor_db)
    voiced = np.where(db >= thresh)[0]
    return float((voiced[-1] + 1) * n / sr) if len(voiced) else 0.0


def _heard_words(path: Path) -> list[dict]:
    import mlx_whisper

    from evals.audioutil import WHISPER_MODEL
    r = mlx_whisper.transcribe(str(path), path_or_hf_repo=WHISPER_MODEL,
                               word_timestamps=True)
    return [w for s in r["segments"] for w in s.get("words", [])]


def check_transcript(ref_path: Path, ref_text: str, source: str,
                     tail_slack: float = 0.35) -> list[str]:
    """Gate 1. Returns a list of problems (empty = pass)."""
    problems: list[str] = []
    words = _heard_words(ref_path)
    if not words:
        return [f"whisper heard no speech in {ref_path.name}"]
    end = _speech_end(ref_path)
    tail = [w for w in words if float(w["start"]) > end + tail_slack]
    heard = " ".join(w["word"] for w in words if w not in tail)
    if tail:
        phrase = " ".join(w["word"].strip() for w in tail)
        if source == "whisper":
            problems.append(
                f"reference transcript was auto-generated by whisper and contains a "
                f"hallucinated tail after speech ends at {end:.1f}s: {phrase!r}. "
                f"Write voices/{ref_path.stem}.ref_text.txt with the exact spoken words.")
        else:
            # Informational only: the sidecar is what the model sees.
            print(f"  preflight: whisper hallucinates {phrase!r} over the reference's "
                  f"silent tail; sidecar transcript in use, ignoring", flush=True)
    ref_tokens, heard_tokens = set(_alpha(ref_text)), set(_alpha(heard))
    if ref_tokens:
        contain_ref = len(ref_tokens & heard_tokens) / len(ref_tokens)
        contain_heard = len(ref_tokens & heard_tokens) / max(1, len(heard_tokens))
        if min(contain_ref, contain_heard) < float(PREFLIGHT_CFG.get("min_transcript_agreement", 0.8)):
            problems.append(
                f"reference transcript ({source}) disagrees with the audio: "
                f"{contain_ref:.0%} of its words heard, {contain_heard:.0%} of heard words "
                f"present. Transcript: {ref_text[:90]!r} / heard: {heard[:90]!r}")
    return problems


def check_canaries(engine, ref_path: Path, n: int | None = None) -> tuple[list[str], dict]:
    """Gate 2. Returns (problems, metrics)."""
    import soundfile as sf

    from evals.audioutil import transcribe
    from evals.textutil import asr_normalize, wer
    n = int(n or PREFLIGHT_CFG.get("canaries", 3))
    min_sim = float(PREFLIGHT_CFG.get("min_similarity", 0.60))
    max_wer = float(PREFLIGHT_CFG.get("max_wer", 0.25))
    texts = (CANARY_TEXTS * ((n // len(CANARY_TEXTS)) + 1))[:n]

    try:
        from resemblyzer import VoiceEncoder, preprocess_wav
        enc = VoiceEncoder(verbose=False)
        ref_emb = enc.embed_utterance(preprocess_wav(str(ref_path)))
    except Exception:
        enc = ref_emb = None

    problems: list[str] = []
    metrics: dict = {"canaries": [], "judge": "llm"}
    tmp = Path(tempfile.mkdtemp(prefix="preflight_"))
    for i, text in enumerate(texts):
        audio = engine.synthesize(text)
        p = tmp / f"canary{i}.wav"
        sf.write(str(p), audio, SAMPLE_RATE)
        heard = transcribe(p).strip()
        row = {"text": text, "heard": heard, "seconds": round(len(audio) / SAMPLE_RATE, 2)}
        try:
            from evals.checks.s5_render import _review_take
            review = _review_take(text, heard, JUDGE_MODEL)
            row["verdict"] = review["verdict"]
            row["issues"] = review.get("issues", [])
            if review["verdict"] == "retake":
                problems.append(f"canary {i} judged retake ({','.join(row['issues'])}): "
                                f"{review.get('reason', '')[:100]} | heard {heard[:80]!r}")
        except Exception:  # Ollama down: deterministic fallback
            metrics["judge"] = "wer-fallback"
            w = wer(asr_normalize(text), asr_normalize(heard))
            row["wer"] = round(w, 3)
            if w > max_wer:
                problems.append(f"canary {i} WER {w:.2f} > {max_wer} | heard {heard[:80]!r}")
        if enc is not None:
            try:
                sim = float(np.dot(ref_emb, enc.embed_utterance(preprocess_wav(str(p)))))
                row["similarity"] = round(sim, 3)
                if sim < min_sim:
                    problems.append(f"canary {i} speaker similarity {sim:.2f} < {min_sim}: "
                                    f"clone drifted from the reference voice")
            except Exception:
                pass
        metrics["canaries"].append(row)
    return problems, metrics


def _cache_key(engine, params: dict) -> str:
    raw = f"{PREFLIGHT_VERSION}|{params.get('model_id')}|{params.get('voice_sha')}|" \
          f"{hashlib.sha256(engine._ref_text.encode()).hexdigest()[:12]}|{JUDGE_MODEL}"
    return hashlib.sha256(raw.encode()).hexdigest()[:16]


def preflight(engine, params: dict) -> dict:
    """Run both gates for a cloned-voice engine. Passing results are cached
    by (audio, transcript, model) so supervisor relaunches don't repeat the
    ten-minute check; a failure raises VoicePreflightError and is not cached,
    so fixing the voice re-runs the gate."""
    ref_path = Path(engine.reference_wav)
    if not ref_path.is_absolute():
        ref_path = ROOT / ref_path
    key = _cache_key(engine, params)
    cache = CACHE_DIR / f"{key}.json"
    if cache.exists():
        d = json.loads(cache.read_text())
        print(f"  voice preflight: cached pass for {ref_path.name} "
              f"({d.get('ts', '')[:16]})", flush=True)
        return d

    print(f"  voice preflight: {ref_path.name} (transcript from "
          f"{getattr(engine, '_ref_text_source', 'unknown')})", flush=True)
    problems = check_transcript(ref_path, engine._ref_text,
                                getattr(engine, "_ref_text_source", "unknown"))
    metrics: dict = {}
    if not problems:  # canaries are pointless with a known-bad transcript
        problems, metrics = check_canaries(engine, ref_path)
    if problems:
        msg = "\n  - ".join([f"voice preflight FAILED for {ref_path.name}; not rendering:"]
                            + problems)
        print(msg, flush=True)
        raise VoicePreflightError(msg)
    result = {"ok": True, "voice": ref_path.name, "ts": time.strftime("%Y-%m-%dT%H:%M:%S"),
              "transcript_source": getattr(engine, "_ref_text_source", "unknown"), **metrics}
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    cache.write_text(json.dumps(result, indent=1))
    sims = [c.get("similarity") for c in metrics.get("canaries", []) if c.get("similarity")]
    print(f"  voice preflight: pass ({len(metrics.get('canaries', []))} canaries, judge="
          f"{metrics.get('judge')}, similarity {min(sims):.2f}-{max(sims):.2f})"
          if sims else "  voice preflight: pass", flush=True)
    return result
